Repository Paris-Squad-S2/San3a, pull requests merged in 2025-08, with the labels that each got.

#47 Feature/register
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/paris_2/san3a/MainActivity.kt
  app/src/main/java/com/paris_2/san3a/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/paris_2/san3a/data/repository/BaseRepository.kt
  app/src/main/java/com/paris_2/san3a/data/repository/ChatRepositoryImpl.kt
  app/src/main/java/com/paris_2/san3a/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/paris_2/san3a/data/repository/MessageRepositoryImpl.kt
  app/src/main/java/com/paris_2/san3a/data/repository/OnboardingRepositoryImpl.kt
  app/src/main/java/com/paris_2/san3a/data/service/auth/AuthApiServices.kt
  app/src/main/java/com/paris_2/san3a/data/source/AppPreferences.kt
  app/src/main/java/com/paris_2/san3a/data/source/remote/auth/AuthRemoteDataSource.kt
  app/src/main/java/com/paris_2/san3a/data/source/remote/auth/AuthRemoteDataSourceImpl.kt
  app/src/main/java/com/paris_2/san3a/data/source/remote/auth/dto/OtpDto.kt
  app/src/main/java/com/paris_2/san3a/data/utils/NetworkConnectionChecker.kt
  app/src/main/java/com/paris_2/san3a/di/appModule.kt
  app/src/main/java/com/paris_2/san3a/di/dataModule.kt
  app/src/main/java/com/paris_2/san3a/di/repositoryModule.kt
  app/src/main/java/com/paris_2/san3a/di/uiModule.kt
  app/src/main/java/com/paris_2/san3a/di/useCaseModule.kt
  app/src/main/java/com/paris_2/san3a/domain/San3aExceptionTree.kt
  app/src/main/java/com/paris_2/san3a/domain/repository/AuthRepository.kt
  app/src/main/java/com/paris_2/san3a/domain/repository/OnboardingRepository.kt
  app/src/main/java/com/paris_2/san3a/domain/usecase/IsOnboardingCompletedUseCase.kt
  app/src/main/java/com/paris_2/san3a/domain/usecase/IsPhoneNumberSavedUseCase.kt
  app/src/main/java/com/paris_2/san3a/domain/usecase/SavePhoneNumberUseCase.kt
  app/src/main/java/com/paris_2/san3a/domain/usecase/SendOtpUseCase.kt
  app/src/main/java/com/paris_2/san3a/domain/usecase/SetOnboardingCompletedUseCase.kt
  app/src/main/java/com/paris_2/san3a/presentation/navigation/Destinations.kt
  app/src/main/java/com/paris_2/san3a/presentation/navigation/NavGraph.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/otpScreen/OTPRegisterListenerInteraction.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/otpScreen/OTPRegisterScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/otpScreen/OTPRegisterUiState.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/otpScreen/OTPRegisterViewModel.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/registerScreen/PhoneNumberVisualTransformation.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/registerScreen/RegisterInteractionListener.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/registerScreen/RegisterScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/registerScreen/RegisterUiState.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/registerScreen/RegisterViewModel.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/splash/SplashScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/shared/components/AppBackButton.kt
  app/src/main/java/com/paris_2/san3a/presentation/shared/components/AppTextField.kt
  app/src/main/java/com/paris_2/san3a/presentation/shared/components/CountryDropdown.kt
  app/src/main/java/com/paris_2/san3a/presentation/shared/components/OTPInputTextField.kt
  app/src/main/res/drawable/ic_eg_flag.png
  app/src/main/res/drawable/ic_logo_white_background.xml
  app/src/main/res/drawable/image_otp.png
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#46 Add Account Setup logic
  app/build.gradle.kts
  app/src/main/java/com/paris_2/san3a/data/repository/UserRepositoryImp.kt
  app/src/main/java/com/paris_2/san3a/data/service/firestore/FireStoreService.kt
  app/src/main/java/com/paris_2/san3a/data/service/firestore/FireStoreServiceImpl.kt
  app/src/main/java/com/paris_2/san3a/data/source/remote/UserRemoteDataSourceImp.kt
  app/src/main/java/com/paris_2/san3a/data/source/remote/tempFile.kt
  app/src/main/java/com/paris_2/san3a/di/dataModule.kt
  app/src/main/java/com/paris_2/san3a/di/repositoryModule.kt
  app/src/main/java/com/paris_2/san3a/di/useCaseModule.kt
  app/src/main/java/com/paris_2/san3a/di/viewModelModule.kt
  app/src/main/java/com/paris_2/san3a/domain/San3aExceptionTree.kt
  app/src/main/java/com/paris_2/san3a/domain/entity/AccountSetupStep.kt
  app/src/main/java/com/paris_2/san3a/domain/entity/Location.kt
  app/src/main/java/com/paris_2/san3a/domain/entity/User.kt
  app/src/main/java/com/paris_2/san3a/domain/repository/UserRemoteDataSource.kt
  app/src/main/java/com/paris_2/san3a/domain/repository/UserRepository.kt
  app/src/main/java/com/paris_2/san3a/domain/source/local/UserLocalDataSource.kt
  app/src/main/java/com/paris_2/san3a/domain/usecase/GetAccountTypeUsecase.kt
  app/src/main/java/com/paris_2/san3a/domain/usecase/SetUpAccountUseCase.kt
  gradle/libs.versions.toml
Labels: feature

#50 start network checker in Application
  app/src/main/java/com/paris_2/san3a/San3aApplication.kt
  app/src/main/java/com/paris_2/san3a/data/utils/NetworkConnectionChecker.kt
  app/src/main/java/com/paris_2/san3a/di/repositoryModule.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/registerScreen/RegisterUiState.kt
  app/src/main/res/drawable/ic_palestine_flag.png
Labels: bug

#59 implement GetUserUseCase and GetWorkMediaUseCase
  app/src/main/java/com/paris_2/san3a/data/repository/UserRepositoryImp.kt
  app/src/main/java/com/paris_2/san3a/data/source/remote/UserRemoteDataSourceImp.kt
  app/src/main/java/com/paris_2/san3a/di/useCaseModule.kt
  app/src/main/java/com/paris_2/san3a/domain/San3aExceptionTree.kt
  app/src/main/java/com/paris_2/san3a/domain/entity/User.kt
  app/src/main/java/com/paris_2/san3a/domain/repository/UserRemoteDataSource.kt
  app/src/main/java/com/paris_2/san3a/domain/repository/UserRepository.kt
  app/src/main/java/com/paris_2/san3a/domain/usecase/GetUserUseCase.kt
  app/src/main/java/com/paris_2/san3a/domain/usecase/GetWorkMediaUseCase.kt
Labels: enhancement

#56 Feature/user profile section components
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/UserProfileSection.kt
  app/src/main/java/com/paris_2/san3a/presentation/shared/components/CraftsmanAvatar.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#60 add setting account items
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/components/LogoutItem.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/components/SettingAccountItems.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/components/SettingItem.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/registerScreen/RegisterScreen.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#61 Feature/more screen components
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/components/BecomeCraftsmanCard.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/components/EditProfileBottomSheet.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/components/EditProfileBottomSheetContent.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/components/LanguageContent.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/components/LogoutBottomSheet.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/myRequest/component/RequestCard.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/otpScreen/OTPRegisterScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/shared/components/AdCard.kt
  app/src/main/java/com/paris_2/san3a/presentation/shared/components/AppButton.kt
  app/src/main/java/com/paris_2/san3a/presentation/shared/components/AppTextField.kt
  app/src/main/java/com/paris_2/san3a/presentation/shared/components/LanguageSelector.kt
  app/src/main/res/drawable/ic_eg_fflag.xml
  app/src/main/res/drawable/ic_ukk_flag.xml
  app/src/main/res/drawable/logout.png
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#72 Add Feature Search And Search With Voice Recognition
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/customer/CustomerHomeInteractionListener.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/customer/CustomerHomeScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/customer/CustomerHomeViewModel.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/customer/CustomerUIState.kt
  app/src/main/java/com/paris_2/san3a/presentation/shared/components/SearchBar.kt
  app/src/main/res/drawable-hdpi/img_no_search_result.png
  app/src/main/res/drawable-mdpi/img_no_search_result.png
  app/src/main/res/drawable-xhdpi/img_no_search_result.png
  app/src/main/res/drawable-xxhdpi/img_no_search_result.png
  app/src/main/res/drawable-xxxhdpi/img_no_search_result.png
  app/src/main/res/drawable/ic_microphone.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#74 Refactor/more
  app/src/main/java/com/paris_2/san3a/data/repository/ProfileRepositoryImpl.kt
  app/src/main/java/com/paris_2/san3a/data/source/local/AppVersionDataSource.kt
  app/src/main/java/com/paris_2/san3a/data/source/local/LocalDataStore.kt
  app/src/main/java/com/paris_2/san3a/data/source/local/LocalDataStoreImpl.kt
  app/src/main/java/com/paris_2/san3a/di/dataModule.kt
  app/src/main/java/com/paris_2/san3a/di/useCaseModule.kt
  app/src/main/java/com/paris_2/san3a/domain/repository/ProfileRepository.kt
  app/src/main/java/com/paris_2/san3a/domain/usecase/GetVersionNameUseCase.kt
  app/src/main/java/com/paris_2/san3a/presentation/mapper/UserMapper.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/components/EditProfileBottomSheet.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/components/LogoutItem.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/components/SettingItems.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/locationScreen/LocationScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/moreScreen/MoreInteractionListener.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/moreScreen/MoreScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/more/moreScreen/MoreViewModel.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/myService/MyServiceScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/myService/MyServiceViewModel.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/verification/VerificationInteractionListener.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/verification/VerificationScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/verification/VerificationViewModel.kt
  app/src/main/java/com/paris_2/san3a/presentation/shared/components/AdCard.kt
  app/src/main/java/com/paris_2/san3a/presentation/utill/SaveAppLanguage.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#79 fix-bug/inconsistent-top-app-bar-and-background-of-the-status-bar
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/craftsman/CraftsmanHomeScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/customer/CustomerHomeScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/shared/components/AppBar.kt
Labels: bug

#78 fix bug when change to craftsman in home
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/customer/CustomerHomeViewModel.kt
Labels: bug

#81 update otp register view model
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/otpScreen/OTPRegisterListenerInteraction.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/otpScreen/OTPRegisterScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/otpScreen/OTPRegisterUiState.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/otpScreen/OTPRegisterViewModel.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#93 Bug fix/fix exception when save the same image
  app/src/main/java/com/paris_2/san3a/data/source/remote/storage/FirebaseStorageDataSource.kt
  app/src/main/java/com/paris_2/san3a/data/source/remote/storage/StorageException.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/account/AccountViewModel.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/customer/CustomerHomeViewModel.kt
Labels: fix bug

#111 Refactor/home app bar
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/craftsman/CraftsmanHomeScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/customer/CustomerHomeScreen.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#116 refactor my service view model
  app/src/main/java/com/paris_2/san3a/presentation/screen/myService/MyServiceScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/myService/MyServiceViewModel.kt
Labels: enhancement

#131 Refactor/home
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/craftsman/CraftsmanHomeScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/craftsman/CraftsmanHomeViewModel.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/craftsman/CraftsmanInteractionListener.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/customer/CustomerHomeScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/customer/CustomerHomeViewModel.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/home/util/getGreetingMessage.kt
Labels: enhancement

#144 bugfix/ui-issues
  app/src/main/java/com/paris_2/san3a/presentation/screen/account/components/LocationContent.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/account/components/ProfileContent.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/account/components/ShowYourWorkContent.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/onboarding/components/Offers.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/register/components/RegisterBottomSheet.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/requestDetails/components/RequestInfoIconTextRow.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/requestDetails/craftsman/CraftsManRequestDetailsScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/screen/requestDetails/customer/CustomerRequestDetailsScreen.kt
  app/src/main/java/com/paris_2/san3a/presentation/shared/components/CraftsmanOffer.kt
Labels: fix bug
